data:
  params:
    dataset: fMRI
    seed:
      #id: [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
      id: [1, 2, 3, 5, 6]
  options:
    path: ../data/fMRI
    scriptname: prepare_dataset

results:
  name: fmri_diffan_tuning2
  plots: True
  metrics:
    - s_f1
    - w_f1

algorithms:
  - id: dummy
    script:
      file: dummy/dummy.py
      env: dodiscover
  
  - id: pcmci
    hparams:
      alpha: [0.05]
      cond_test: ['par_corr']
    script:
      file: tigramite/main.py
      param: pcmci
      env: tigramite