data:
  params:
    dataset: finance
    seed:
      id: ['manyinputs', 'random-rels_20_1_3', 'random-rels_20_1A', 'random-rels_20_1B', 'random-rels_20_1C', 'random-rels_20_1D', 'random-rels_20_1E']
  options:
    path: ../data/FinanceCPT
    scriptname: prepare_dataset

results:
  name: real_finance
  plots: True
  metrics:
    - s_f1
    - w_f1

algorithms:
  - id: dummy
    script:
      file: dummy/dummy.py
      env: dodiscover
  
  - id: cam
    hparams:
      alpha: [0.01, 0.05]
    script:
      file: dodisc/dodiscover-main/dodisc.py
      param: cam
      env: dodiscover
  
  - id: score
    hparams:
      eta_g: [0.001]
      eta_h: [0.001]
      alpha: [0.01, 0.05]
    script:
      file: dodisc/dodiscover-main/dodisc.py
      param: score
      env: dodiscover
  
  - id: das
    hparams:
      eta_g: [0.001]
      eta_h: [0.001]
      alpha: [0.01, 0.05]
    script:
      file: dodisc/dodiscover-main/dodisc.py
      param: das
      env: dodiscover
  
  - id: nogam
    hparams:
      ridge_alpha: [0.01]
      ridge_gamma: [0.1]
      eta_g: [0.001]
      eta_h: [0.001]
      alpha: [0.01, 0.05]
    script:
      file: dodisc/dodiscover-main/dodisc.py
      param: nogam
      env: dodiscover
  
  - id: pcmci
    hparams:
      alpha: [0.01, 0.05]
      cond_test: ['par_corr', 'cmi_knn']
    script:
      file: tigramite/main.py
      param: pcmci
      env: tigramite

  - id: pcmci+
    hparams:
      alpha: [0.01, 0.05]
      cond_test: ['par_corr', 'cmi_knn']
    script:
      file: tigramite/main.py
      param: pcmci_plus
      env: tigramite
  
  - id: varlingam
    hparams:
      alpha: [0.01, 0.05]
    script:
      file: lingam/main.py
      env: ../../envs/lingam.yml
  
  - id: dynotears
    hparams:
      w_thres: [0.01]
      lambda_w: [0.01, 0.05]
      lambda_a: [0.01, 0.05]
    script:
      file: dynotears/main.py
      env: ../../envs/causalnex.yml
  
  - id: tcdf
    hparams:
      epochs: [1000]
      h_layers: [0, 1]
      lr: [0.01]
    script:
      file: tcdf/TCDF-master/main.py
      env: tcdf

r-algorithms:
  - id: timino
    hparams:
      alpha: [0.01, 0.05]
    script:
      file: timino/main.R
      env: timino