data:
  params:
    n: [500]
    features: [3]
    n_lag: [1]
    prob_ar: [0.3]
    prob_edge: [0.4]
    seed:
      id: [1]

results:
  name: small_7
  plots: False
  metrics:
    - s_f1
    - w_f1
  repeats: 3

algorithms:
  - id: dummy
    script:
      file: dummy/dummy.py
      env: dodiscover
  
  - id: pcmci
    hparams:
      alpha: [0.05]
      cond_test: ['par_corr']
    script:
      file: tigramite/main.py
      param: pcmci
      env: tigramite